

/****** Object:  Table [etl].[F4101_item_master]    Script Date: 6/13/2017 5:39:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Integration].[F4101_item_master_Staging](
	[IMITM__item_number_short] [numeric](8, 0) NOT NULL,
	[IMLITM_item_number] [char](25) NOT NULL,
	[IMAITM__3rd_item_number] [char](25) NOT NULL,
	[IMDSC1_description] [char](30) NOT NULL,
	[IMDSC2_description_2] [char](30) NOT NULL,
	[IMSRTX_search_text] [char](30) NOT NULL,
	[IMALN__search_text_compressed] [char](30) NOT NULL,
	[IMSRP1_sales_catalog_section] [char](3) NOT NULL,
	[IMSRP2_sub_section] [char](3) NOT NULL,
	[IMSRP3_sales_category_code_3] [char](3) NOT NULL,
	[IMSRP4_sales_category_code_4] [char](3) NOT NULL,
	[IMSRP5_sales_category_code_5] [char](3) NOT NULL,
	[IMSRP6_category_code_6] [char](6) NOT NULL,
	[IMSRP7_category_code_7] [char](6) NOT NULL,
	[IMSRP8_category_code_8] [char](6) NOT NULL,
	[IMSRP9_category_code_9] [char](6) NOT NULL,
	[IMSRP0_category_code_10] [char](6) NOT NULL,
	[IMPRP1_commodity_class] [char](3) NOT NULL,
	[IMPRP2_commodity_sub_class] [char](3) NOT NULL,
	[IMPRP3_supplier_rebate_code] [char](3) NOT NULL,
	[IMPRP4_master_planning_family] [char](3) NOT NULL,
	[IMPRP5_landed_cost_rule] [char](3) NOT NULL,
	[IMPRP6_item_dimension_group] [char](6) NOT NULL,
	[IMPRP7_warehouse_process_grp_1] [char](6) NOT NULL,
	[IMPRP8_warehouse_process_grp_2] [char](6) NOT NULL,
	[IMPRP9_warehouse_process_grp_3] [char](6) NOT NULL,
	[IMPRP0_item_pool_code] [char](6) NOT NULL,
	[IMCDCD_commodity_code] [char](15) NOT NULL,
	[IMPDGR_product_group] [char](3) NOT NULL,
	[IMDSGP_dispatch_group] [char](3) NOT NULL,
	[IMPRGR_item_price_group] [char](8) NOT NULL,
	[IMRPRC_basket_reprice_group] [char](8) NOT NULL,
	[IMORPR_order_reprice_group] [char](8) NOT NULL,
	[IMBUYR_buyer_number] [numeric](8, 0) NOT NULL,
	[IMDRAW_drawing_number] [char](20) NOT NULL,
	[IMRVNO_last_revision_no] [char](3) NOT NULL,
	[IMDSZE_drawing_size] [char](1) NOT NULL,
	[IMVCUD_volume_cubic_dimensions] [numeric](15, 4) NOT NULL,
	[IMCARS_carrier_number] [numeric](8, 0) NOT NULL,
	[IMCARP_preferred_carrier_purchasing] [numeric](8, 0) NOT NULL,
	[IMSHCN_shipping_conditions_code] [char](3) NOT NULL,
	[IMSHCM_shipping_commodity_class] [char](3) NOT NULL,
	[IMUOM1_unit_of_measure] [char](2) NOT NULL,
	[IMUOM2_secondary_uom] [char](2) NOT NULL,
	[IMUOM3_purchasing_uom] [char](2) NOT NULL,
	[IMUOM4_pricing_uom] [char](2) NOT NULL,
	[IMUOM6_shipping_uom] [char](2) NOT NULL,
	[IMUOM8_production_uom] [char](2) NOT NULL,
	[IMUOM9_component_uom] [char](2) NOT NULL,
	[IMUWUM_unit_of_measure_weight] [char](2) NOT NULL,
	[IMUVM1_unit_of_measure_volume] [char](2) NOT NULL,
	[IMSUTM_stocking_um] [char](2) NOT NULL,
	[IMUMVW_psauvolume_or_weight] [char](1) NOT NULL,
	[IMCYCL_cycle_count_category] [char](3) NOT NULL,
	[IMGLPT_gl_category] [char](4) NOT NULL,
	[IMPLEV_sales_price_level] [char](1) NOT NULL,
	[IMPPLV_purchase_price_level] [char](1) NOT NULL,
	[IMCLEV_inventory_cost_level] [char](1) NOT NULL,
	[IMPRPO_gradepotency_pricing] [char](1) NOT NULL,
	[IMCKAV_check_availability_yn] [char](1) NOT NULL,
	[IMBPFG_bulkpacked_flag] [char](1) NOT NULL,
	[IMSRCE_layer_code_source] [char](1) NOT NULL,
	[IMOT1Y_potency_control] [char](1) NOT NULL,
	[IMOT2Y_grade_control] [char](1) NOT NULL,
	[IMSTDP_standard_potency] [numeric](15, 3) NOT NULL,
	[IMFRMP_from_potency] [numeric](15, 3) NOT NULL,
	[IMTHRP_thru_potency] [numeric](15, 3) NOT NULL,
	[IMSTDG_standard_grade] [char](3) NOT NULL,
	[IMFRGD_from_grade] [char](3) NOT NULL,
	[IMTHGD_thru_grade] [char](3) NOT NULL,
	[IMCOTY_component_type] [char](1) NOT NULL,
	[IMSTKT_stocking_type] [char](1) NOT NULL,
	[IMLNTY_line_type] [char](2) NOT NULL,
	[IMCONT_contract_item] [char](1) NOT NULL,
	[IMBACK_backorders_allowed_yn] [char](1) NOT NULL,
	[IMIFLA_item_flash_message] [char](2) NOT NULL,
	[IMTFLA_std_uom_conversion] [char](2) NOT NULL,
	[IMINMG_print_message] [char](10) NOT NULL,
	[IMABCS_abc_code_1_sales] [char](1) NOT NULL,
	[IMABCM_abc_code_2_margin] [char](1) NOT NULL,
	[IMABCI_abc_code_3_investment] [char](1) NOT NULL,
	[IMOVR__abc_code_override_indicator] [char](1) NOT NULL,
	[IMWARR_warranty_item_group] [char](8) NOT NULL,
	[IMCMCG_commission_category] [char](8) NOT NULL,
	[IMSRNR_serial_no_required] [char](1) NOT NULL,
	[IMPMTH_kit_pricing_method] [char](1) NOT NULL,
	[IMFIFO_fifo_processing] [char](1) NOT NULL,
	[IMLOTS_lot_status_code] [char](1) NOT NULL,
	[IMSLD__shelf_life_days] [numeric](6, 0) NOT NULL,
	[IMANPL_planner_number] [numeric](8, 0) NOT NULL,
	[IMMPST_planning_code] [char](1) NOT NULL,
	[IMPCTM_percent_margin] [numeric](15, 3) NOT NULL,
	[IMMMPC_margin_maintenance_pct] [numeric](15, 3) NOT NULL,
	[IMPTSC_material_status] [char](2) NOT NULL,
	[IMSNS__round_to_whole_number] [char](1) NOT NULL,
	[IMLTLV_leadtime_level] [numeric](5, 0) NOT NULL,
	[IMLTMF_leadtime_manufacturing] [numeric](5, 0) NOT NULL,
	[IMLTCM_leadtime_cumulative] [numeric](5, 0) NOT NULL,
	[IMOPC__order_policy_code] [char](1) NOT NULL,
	[IMOPV__value_order_policy] [numeric](15, 0) NOT NULL,
	[IMACQ__accounting_cost_quantity] [numeric](15, 0) NOT NULL,
	[IMMLQ__mfg_leadtime_quantity] [numeric](15, 0) NOT NULL,
	[IMLTPU_leadtime_per_unit] [numeric](15, 2) NOT NULL,
	[IMMPSP_planning_fence_rule] [char](1) NOT NULL,
	[IMMRPP_fixedvariable_leadtime] [char](1) NOT NULL,
	[IMITC__issue_type_code] [char](1) NOT NULL,
	[IMORDW_order_with_yn] [char](1) NOT NULL,
	[IMMTF1_planning_fence] [numeric](5, 0) NOT NULL,
	[IMMTF2_freeze_fence] [numeric](5, 0) NOT NULL,
	[IMMTF3_message_display_fence] [numeric](5, 0) NOT NULL,
	[IMMTF4_time_fence] [numeric](5, 0) NOT NULL,
	[IMMTF5_shipment_leadtime_offset] [numeric](5, 0) NOT NULL,
	[IMMTF6_supply_time_fence] [numeric](5, 0) NOT NULL,
	[IMEXPD_expedite_damper_days] [numeric](5, 0) NOT NULL,
	[IMDEFD_defer_damper_days] [numeric](5, 0) NOT NULL,
	[IMSFLT_safety_leadtime] [numeric](5, 0) NOT NULL,
	[IMMAKE_makebuy_code] [char](1) NOT NULL,
	[IMCOBY_cobyproductintermediate] [char](1) NOT NULL,
	[IMLLX__low_level_code] [numeric](3, 0) NOT NULL,
	[IMCMGL_commitment_method] [char](1) NOT NULL,
	[IMCOMH_specific_commitment_days] [numeric](3, 0) NOT NULL,
	[IMCSNN_configured_string_id_next_number] [numeric](8, 0) NOT NULL,
	[IMURCD_user_reserved_code] [char](2) NOT NULL,
	[IMURDT_user_reserved_date] [date] NULL,
	[IMURAT_user_reserved_amount] [numeric](15, 2) NOT NULL,
	[IMURAB_user_reserved_number] [numeric](8, 0) NOT NULL,
	[IMURRF_user_reserved_reference] [char](15) NOT NULL,
	[IMAVRT_replenishment_hours] [numeric](15, 2) NOT NULL,
	[IMUPCN_upc_number] [char](13) NOT NULL,
	[IMSCC0_aggregate_scc_code_pi0] [char](14) NOT NULL,
	[IMUMUP_unit_of_measure_upc] [char](2) NOT NULL,
	[IMUMDF_unit_of_measure_aggregate_upc] [char](2) NOT NULL,
	[IMUMS0_unit_of_measure_sccpi0] [char](2) NOT NULL,
	[IMUMS1_unit_of_measure_sccpi1] [char](2) NOT NULL,
	[IMUMS2_unit_of_measure_sccpi2] [char](2) NOT NULL,
	[IMUMS3_unit_of_measure_sccpi3] [char](2) NOT NULL,
	[IMUMS4_unit_of_measure_sccpi4] [char](2) NOT NULL,
	[IMUMS5_unit_of_measure_sccpi5] [char](2) NOT NULL,
	[IMUMS6_unit_of_measure_sccpi6] [char](2) NOT NULL,
	[IMUMS7_unit_of_measure_sccpi7] [char](2) NOT NULL,
	[IMUMS8_unit_of_measure_sccpi8] [char](2) NOT NULL,
	[IMPILT_purchasing_internal_lead_time] [numeric](5, 0) NOT NULL,
	[IMWTRQ_item_weight_required_yn] [char](1) NOT NULL,
	[IMPOC__i] [char](1) NOT NULL,
	[IMEXPI_explode_item_10] [char](1) NOT NULL,
	[IMCONI_constraint_item_10] [char](1) NOT NULL,
	[IMORSP_allow_order_split_10] [char](1) NOT NULL,
	[IMCNSD_consolidation_days] [numeric](5, 0) NOT NULL,
	[IMCMDM_commitment_date_method] [char](1) NOT NULL,
	[IMLECM_exp_date_calc_method] [char](1) NOT NULL,
	[IMBBDD_best_before_default_days] [numeric](6, 0) NOT NULL,
	[IMSBDD_sell_by_default_days] [numeric](6, 0) NOT NULL,
	[IMLEDD_mfg_lot_effective_days] [numeric](6, 0) NOT NULL,
	[IMPEFD_purchasing_lot_effective_days] [numeric](6, 0) NOT NULL,
	[IMU1DD_user_lot_date_1_default_days] [numeric](6, 0) NOT NULL,
	[IMU2DD_user_lot_date_2_default_days] [numeric](6, 0) NOT NULL,
	[IMU3DD_user_lot_date_3_default_days] [numeric](6, 0) NOT NULL,
	[IMU4DD_user_lot_date_4_default_days] [numeric](6, 0) NOT NULL,
	[IMU5DD_user_lot_date_5_default_days] [numeric](6, 0) NOT NULL,
	[IMTORG_transaction_originator] [char](10) NOT NULL,
	[IMUSER_user_id] [char](10) NOT NULL,
	[IMPID__program_id] [char](10) NOT NULL,
	[IMJOBN_work_station_id] [char](10) NOT NULL,
	[IMUPMJ_date_updated] [date] NULL,
	[IMTDAY_time_of_day] [numeric](6, 0) NOT NULL,
 CONSTRAINT [PK_F4101_item_master] PRIMARY KEY CLUSTERED 
(
	[IMITM__item_number_short] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [USERDATA]
) ON [USERDATA]

GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [F4101_item_master_u_indx_01]    Script Date: 6/13/2017 5:39:26 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [F4101_item_master_u_indx_01] ON [Integration].[F4101_item_master_Staging]
(
	[IMLITM_item_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [USERDATA]
GO


