dbMemo "SQL" ="EXEC fg.order_load_proc @bDebug=0"
dbMemo "Connect" ="ODBC;DSN=BRSales;Description=BRSales;Trusted_Connection=Yes;DATABASE=DEV_BRSales"
    ";Network=DBMSSOCN;"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbBoolean "LogMessages" ="0"
Begin
End
