dbMemo "SQL" ="EXEC fg.order_update_proc @bDebug=1\015\012"
dbMemo "Connect" ="ODBC;DSN=DEV_BRSales;Description=BRSales;Trusted_Connection=Yes;DATABASE=DEV_BRS"
    "ales;Network=DBMSSOCN;"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbBoolean "LogMessages" ="-1"
Begin
End
