USE [BRSales]
GO

/****** Object:  Table [etl].[F0101_address_book_master]    Script Date: 6/13/2017 5:29:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [etl].[F0101_address_book_master](
	[ABAN8__billto] [numeric](8, 0) NOT NULL,
	[ABALKY_long_address_number] [char](20) NOT NULL,
	[ABTAX__tax_id] [char](20) NOT NULL,
	[ABALPH_alpha_name] [char](40) NOT NULL,
	[ABDC___description_compressed] [char](40) NOT NULL,
	[ABMCU__business_unit] [char](12) NOT NULL,
	[ABSIC__industry_classification] [char](10) NOT NULL,
	[ABLNGP_language] [char](2) NOT NULL,
	[ABAT1__search_type] [char](3) NOT NULL,
	[ABCM___credit_message] [char](2) NOT NULL,
	[ABTAXC_personcorporation_code] [char](1) NOT NULL,
	[ABAT2__arap_netting_y] [char](1) NOT NULL,
	[ABAT3__address_type_3_yn] [char](1) NOT NULL,
	[ABAT4__address_type_4_yn] [char](1) NOT NULL,
	[ABAT5__address_type_5_yn] [char](1) NOT NULL,
	[ABATP__payables_ynm] [char](1) NOT NULL,
	[ABATR__receivables_yn] [char](1) NOT NULL,
	[ABATPR_status] [char](1) NOT NULL,
	[ABAB3__miscellaneous_code] [char](1) NOT NULL,
	[ABATE__employee_yn] [char](1) NOT NULL,
	[ABSBLI_subledger_inactive_code] [char](1) NOT NULL,
	[ABEFTB_start_effective_date] [numeric](6, 0) NOT NULL,
	[ABAN81__1st_address_number] [numeric](8, 0) NOT NULL,
	[ABAN82__2nd_address_number] [numeric](8, 0) NOT NULL,
	[ABAN83__3rd_address_number] [numeric](8, 0) NOT NULL,
	[ABAN84__4th_address_number] [numeric](8, 0) NOT NULL,
	[ABAN86__5th_address_number] [numeric](8, 0) NOT NULL,
	[ABAN85_factorspecial_payee_hard_coded] [numeric](8, 0) NOT NULL,
	[ABAC01_customer_profession] [char](3) NOT NULL,
	[ABAC02_account_representative] [char](3) NOT NULL,
	[ABAC03_category_code_03] [char](3) NOT NULL,
	[ABAC04_geographic_region] [char](3) NOT NULL,
	[ABAC05_category_code_05] [char](3) NOT NULL,
	[ABAC06_category_code_06] [char](3) NOT NULL,
	[ABAC07__1099_reporting] [char](3) NOT NULL,
	[ABAC08_category_code_08] [char](3) NOT NULL,
	[ABAC09_category_code_09] [char](3) NOT NULL,
	[ABAC10_category_code_10] [char](3) NOT NULL,
	[ABAC11_sales_region] [char](3) NOT NULL,
	[ABAC12_category_code_12] [char](3) NOT NULL,
	[ABAC13_line_of_business] [char](3) NOT NULL,
	[ABAC14_foreign_country_code] [char](3) NOT NULL,
	[ABAC15_category_code_15] [char](3) NOT NULL,
	[ABAC16_category_code_16] [char](3) NOT NULL,
	[ABAC17_category_code_17] [char](3) NOT NULL,
	[ABAC18_category_code_18] [char](3) NOT NULL,
	[ABAC19_category_code_19] [char](3) NOT NULL,
	[ABAC20_category_code_20] [char](3) NOT NULL,
	[ABAC21_category_code_21] [char](3) NOT NULL,
	[ABAC22_category_code_22] [char](3) NOT NULL,
	[ABAC23_category_code_23] [char](3) NOT NULL,
	[ABAC24_category_code_24] [char](3) NOT NULL,
	[ABAC25_category_code_25] [char](3) NOT NULL,
	[ABAC26_category_code_26] [char](3) NOT NULL,
	[ABAC27_category_code_27] [char](3) NOT NULL,
	[ABAC28_category_code_28] [char](3) NOT NULL,
	[ABAC29_category_code_29] [char](3) NOT NULL,
	[ABAC30_category_code_30] [char](3) NOT NULL,
	[ABGLBA_gl_bank_account] [char](8) NOT NULL,
	[ABPTI__time_scheduled_in] [numeric](6, 0) NOT NULL,
	[ABPDI__date_scheduled_in_JDT] [numeric](6, 0) NOT NULL,
	[ABMSGA_cleared_y] [char](1) NOT NULL,
	[ABRMK__remark] [char](30) NOT NULL,
	[ABTXCT_certificate] [char](20) NOT NULL,
	[ABTX2__addl_ind_tax_id] [char](20) NOT NULL,
	[ABALP1_secondary_alpha_name] [char](40) NOT NULL,
	[ABURCD_user_reserved_code] [char](2) NOT NULL,
	[ABURDT_user_reserved_date_JDT] [numeric](6, 0) NOT NULL,
	[ABURAT_user_reserved_amount] [numeric](15, 2) NOT NULL,
	[ABURAB_user_reserved_number] [numeric](8, 0) NOT NULL,
	[ABURRF_user_reserved_reference] [char](15) NOT NULL,
	[ABEMCD_email_client_designator] [char](1) NOT NULL,
	[ABUSER_user_id] [char](10) NOT NULL,
	[ABPID__program_id] [char](10) NOT NULL,
	[ABUPMJ_date_updated_JDT] [numeric](6, 0) NOT NULL,
	[ABJOBN_work_station_id] [char](10) NOT NULL,
	[ABUPMT_time_last_updated] [numeric](6, 0) NOT NULL,
	[ABTORG_transaction_originator] [char](10) NOT NULL,
	[ABCNCD_consolidation_code] [char](8) NOT NULL,
	[ABPA8__parent_number] [numeric](8, 0) NOT NULL,
	[ABXAB__inactive_code] [char](1) NOT NULL,
	[ABFMDL_templatemodel_flag] [char](1) NOT NULL,
	[ABHLS__homeland_security_flag] [char](1) NOT NULL,
	[ABNACS_naics_code] [char](10) NOT NULL,
	[ABUR1A_user_reserved_field] [char](1) NOT NULL,
	[ABURA1_user_reserved_field] [char](1) NOT NULL,
	[ABFC05_deletion_flag] [char](1) NOT NULL,
	[ABFC06_future_use] [char](1) NOT NULL,
	[ABFC07_future_use] [char](2) NOT NULL,
	[ABFC08_future_use] [char](2) NOT NULL,
	[ABFCD3_future_use_JDT] [numeric](6, 0) NOT NULL,
	[ABFCD4_future_use_JDT] [numeric](6, 0) NOT NULL,
 CONSTRAINT [PK_F0101_address_book_master] PRIMARY KEY CLUSTERED 
(
	[ABAN8__billto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


