--- optimize index, tmc, 7 Jan 18

-- new

-- cust fix

BEGIN TRANSACTION
GO
DROP INDEX IX_BRS_CustomerFSC_History ON dbo.BRS_CustomerFSC_History
GO
ALTER TABLE dbo.BRS_CustomerFSC_History
	DROP CONSTRAINT BRS_CustomerFSC_History_c_pk
GO
ALTER TABLE dbo.BRS_CustomerFSC_History ADD CONSTRAINT
	BRS_CustomerFSC_History_c_pk PRIMARY KEY CLUSTERED 
	(
	FiscalMonth,
	Shipto
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX IX_BRS_CustomerFSC_History ON dbo.BRS_CustomerFSC_History
	(
	Shipto,
	FiscalMonth
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.BRS_CustomerFSC_History SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

-- item fix
ALTER TABLE dbo.BRS_ItemHistory
	DROP CONSTRAINT BRS_ItemHistory_c_pk
GO
ALTER TABLE dbo.BRS_ItemHistory ADD CONSTRAINT
	BRS_ItemHistory_c_pk PRIMARY KEY CLUSTERED 
	(
	FiscalMonth,
	Item
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX BRS_ItemHistory_idx_01 ON dbo.BRS_ItemHistory
	(
	Item,
	FiscalMonth
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON USERDATA
GO
