-- SM tracker admin, tmc, 8 Nov 19

BEGIN TRANSACTION
GO
ALTER TABLE dbo.BRS_CustomerVPA ADD
	FocusCd nchar(5) NOT NULL CONSTRAINT DF_BRS_CustomerVPA_FocusCd DEFAULT ''
GO
ALTER TABLE dbo.BRS_CustomerVPA SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


-- build accounts
UPDATE dbo.BRS_CustomerVPA 
SET FocusCd = 'MMBLD' 
WHERE [VPA] in ('ALEXYEH', 'BECIR', 'CHAN01', 'CHEBAVIV', 'CHOPRARO', 'CREDVALL', 'DANGSTOR', 'DENTARUS', 'DRAKEDAV', 'ELAWOUR', 'HELPARD', 'INFINIT', 'KAVAROS', 'LEEGEORG', 'LIM01', 'MCMANA01', 'MONGA', 'NACH05', 'NORTHRAV', 'OMSGROUP', 'PERSHAD', 'PUBLHLTH', 'REGHLTH', 'RHEE01', 'SDCLUB', 'SMILEDZN', 'SODHI01', 'TOMLEE', 'VISHAL', 'ZAKARIA', 'PEELREGN', 'REGHLTCT', 'REGHLTH3', 'REGHLTH5' )


-- build accounts
UPDATE dbo.BRS_CustomerVPA 
SET FocusCd = 'MMDRP' 
WHERE [VPA] in ('ALBERTA', 'ALDABB06', 'ARG02', 'ASPIRE', 'BRAKRAY', 'CHOW01', 'CORON01', 'CROWLEY', 'DANESHV', 'DHIRKOVI', 'DRCHUN', 'DUNDAS', 'EDWARDS', 'GABER2', 'GRODECKI', 'HERE01', 'HSYGROUP', 'JAUHAL01', 'KHAN001', 'KUP01', 'KWANYUYU', 'PALMER', 'RAHAUSEN', 'SARHAN01', 'SHARMA1', 'SMALIN12', 'SMKING12', 'TRILL01', 'VANKOUGH', 'VERO01')





sELECT vpa, FocusCd  FROM dbo.BRS_CustomerVPA 
WHERE [VPA] in ('ALDABB06', 'ARG02', 'ASPIRE', 'BRAKRAY', 'CHOW01', 'CORON01', 'CROWLEY', 'DANESHV', 'DHIRKOVI', 'DRCHUN', 'DUNDAS', 'EDWARDS', 'GABER2', 'GRODECKI', 'HERE01', 'HSYGROUP', 'JAUHAL01', 'KHAN001', 'KUP01', 'KWANYUYU', 'PALMER', 'RAHAUSEN', 'SARHAN01', 'SHARMA1', 'SMALIN12', 'SMKING12', 'TRILL01', 'VANKOUGH', 'VERO01')


