-- med price add, tmc, 14 Apr 26

BEGIN TRANSACTION
GO
ALTER TABLE dbo.STAGE_BRS_ItemFull ADD
	CurrentMedPrice float(53) NULL
GO
ALTER TABLE dbo.STAGE_BRS_ItemFull SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.BRS_Item ADD
	CurrentMedPrice money NOT NULL CONSTRAINT DF_BRS_Item_CurrentMedPrice DEFAULT 0
GO
ALTER TABLE dbo.BRS_Item SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
