SELECT 

    *
    
FROM 
    OPENQUERY (ESYS_PROD, '

	SELECT
		ADAST, 
		ADITM, 
		ADLITM, 
		ADAITM, 
		ADAN8, 
		ADICID, 
		ADSDGR, 
		ADSDV1, 
		ADSDV2, 
		ADSDV3, 
		ADCRCD, 
		ADUOM, 
		ADMNQ, 
		ADEFTJ as ADEFTJ, ADEXDJ as ADEXDJ, ADBSCD, ADLEDG, ADFRMN, DECIMAL (ADFVTR/10000.0, 8,2) AS ADFVTR, ADFGY, ADATID, ADURCD, ADURDT as ADURDT, CAST((ADURAT)/100.0 AS DEC(15,2)) AS ADURAT, ADURAB, ADURRF, ADUSER, ADPID, ADJOBN, ADUPMJ as ADUPMJ, ADTDAY


	FROM
		ARCPDTA71.F4072
	Where
		ADAST  in( ''DIVPRICE'' ) AND
		adeftj <= CONCAT(CONCAT(''1'',SUBSTR(CHAR(YEAR(CURRENT_DATE)),3,2)), SUBSTR(CHAR(DIGITS(DAYOFYEAR(CURRENT_DATE))),8,3)) and 
		adexdj >= CONCAT(CONCAT(''1'',SUBSTR(CHAR(YEAR(CURRENT_DATE)),3,2)), SUBSTR(CHAR(DIGITS(DAYOFYEAR(CURRENT_DATE))),8,3)) 
')


