-- JDE Access via ODBC linked server
-- updated 3 Nov 16 from Trevor

-- example table pull with friendly field names

--------------------------------------------------------------------------------
-- DROP TABLE Integration.HSIPDTA71_F4101_item_master
--------------------------------------------------------------------------------

SELECT 

    Top 5 
    "IMITM" AS IMITM__item_number_short,
	"IMLITM" AS IMLITM_item_number,
	"IMAITM" AS IMAITM__3rd_item_number,
	"IMDSC1" AS IMDSC1_description,
	"IMDSC2" AS IMDSC2_description_2,
	"IMSRTX" AS IMSRTX_search_text,
	"IMALN" AS IMALN__search_text_compressed,
	"IMSRP1" AS IMSRP1_major_product_class,
	"IMSRP2" AS IMSRP2_sub_major_product_class,
	"IMSRP3" AS IMSRP3_minor_product_class,
	"IMSRP4" AS IMSRP4_sub_minor_product_class,
	"IMSRP5" AS IMSRP5_hazardous_class,
	"IMSRP6" AS IMSRP6_manufacturer,
	"IMSRP7" AS IMSRP7_drug_class,
	"IMSRP8" AS IMSRP8_manuf_dspsearch,
	"IMSRP9" AS IMSRP9_category_code_9,
	"IMSRP0" AS IMSRP0_category_code_10,
	"IMPRP1" AS IMPRP1_commodity_class,
	"IMPRP2" AS IMPRP2_commodity_sub_class,
	"IMPRP3" AS IMPRP3_supplier_rebate_code,
	"IMPRP4" AS IMPRP4_tax_classification,
	"IMPRP5" AS IMPRP5_landed_cost_rule,
	"IMPRP6" AS IMPRP6_item_dimension_group,
	"IMPRP7" AS IMPRP7_warehouse_process_grp_1,
	"IMPRP8" AS IMPRP8_warehouse_process_grp_2,
	"IMPRP9" AS IMPRP9_warehouse_process_grp_3,
	"IMPRP0" AS IMPRP0_commodity_code,
	"IMCDCD" AS IMCDCD_commodity_code,
	"IMPDGR" AS IMPDGR_product_group,
	"IMDSGP" AS IMDSGP_dispatch_group,
	"IMPRGR" AS IMPRGR_item_price_group,
	"IMRPRC" AS IMRPRC_basket_reprice_group,
	"IMORPR" AS IMORPR_order_reprice_group,
	"IMBUYR" AS IMBUYR_buyer_number,
	"IMDRAW" AS IMDRAW_drawing_number,
	"IMRVNO" AS IMRVNO_last_revision_no,
	"IMDSZE" AS IMDSZE_drawing_size,
	"IMVCUD" AS IMVCUD_volume_cubic_dimensions,
	"IMCARS" AS IMCARS_carrier_number,
	"IMCARP" AS IMCARP_preferred_carrier_purchasing,
	"IMSHCN" AS IMSHCN_shipping_conditions_code,
	"IMSHCM" AS IMSHCM_shipping_commodity_class,
	"IMUOM1" AS IMUOM1_unit_of_measure,
	"IMUOM2" AS IMUOM2_secondary_uom,
	"IMUOM3" AS IMUOM3_purchasing_uom,
	"IMUOM4" AS IMUOM4_pricing_uom,
	"IMUOM6" AS IMUOM6_shipping_uom,
	"IMUOM8" AS IMUOM8_production_uom,
	"IMUOM9" AS IMUOM9_component_uom,
	"IMUWUM" AS IMUWUM_unit_of_measure_weight,
	"IMUVM1" AS IMUVM1_unit_of_measure_volume,
	"IMSUTM" AS IMSUTM_stocking_um,
	"IMUMVW" AS IMUMVW_psauvolume_or_weight,
	"IMCYCL" AS IMCYCL_cycle_count_category,
	"IMGLPT" AS IMGLPT_gl_category,
	"IMPLEV" AS IMPLEV_sales_price_level,
	"IMPPLV" AS IMPPLV_purchase_price_level,
	"IMCLEV" AS IMCLEV_inventory_cost_level,
	"IMPRPO" AS IMPRPO_gradepotency_pricing,
	"IMCKAV" AS IMCKAV_check_availability_yn,
	"IMBPFG" AS IMBPFG_bulkpacked_flag,
	"IMSRCE" AS IMSRCE_layer_code_source,
	"IMOT1Y" AS IMOT1Y_potency_control,
	"IMOT2Y" AS IMOT2Y_grade_control,
	"IMSTDP" AS IMSTDP_standard_potency,
	"IMFRMP" AS IMFRMP_from_potency,
	"IMTHRP" AS IMTHRP_thru_potency,
	"IMSTDG" AS IMSTDG_standard_grade,
	"IMFRGD" AS IMFRGD_from_grade,
	"IMTHGD" AS IMTHGD_thru_grade,
	"IMCOTY" AS IMCOTY_component_type,
	"IMSTKT" AS IMSTKT_stocking_type,
	"IMLNTY" AS IMLNTY_line_type,
	"IMCONT" AS IMCONT_contract_item,
	"IMBACK" AS IMBACK_backorders_allowed_yn,
	"IMIFLA" AS IMIFLA_item_flash_message,
	"IMTFLA" AS IMTFLA_std_uom_conversion,
	"IMINMG" AS IMINMG_print_message,
	"IMABCS" AS IMABCS_abc_code_1_sales,
	"IMABCM" AS IMABCM_abc_code_2_margin,
	"IMABCI" AS IMABCI_abc_code_3_investment,
	"IMOVR" AS IMOVR__abc_code_override_indicator,
	"IMWARR" AS IMWARR_warranty_item_group,
	"IMCMCG" AS IMCMCG_commission_category,
	"IMSRNR" AS IMSRNR_serial_no_required,
	"IMPMTH" AS IMPMTH_kit_pricing_method,
	"IMFIFO" AS IMFIFO_fifo_processing,
	"IMLOTS" AS IMLOTS_lot_status_code,
	"IMSLD" AS IMSLD__shelf_life_days,
	"IMANPL" AS IMANPL_planner_number,
	"IMMPST" AS IMMPST_planning_code,
	"IMPCTM" AS IMPCTM_percent_margin,
	"IMMMPC" AS IMMMPC_margin_maintenance_pct,
	"IMPTSC" AS IMPTSC_part_status_code,
	"IMSNS" AS IMSNS__round_to_whole_number,
	"IMLTLV" AS IMLTLV_leadtime_level,
	"IMLTMF" AS IMLTMF_leadtime_manufacturing,
	"IMLTCM" AS IMLTCM_leadtime_cumulative,
	"IMOPC" AS IMOPC__order_policy_code,
	"IMOPV" AS IMOPV__value_order_policy,
	"IMACQ" AS IMACQ__accounting_cost_quantity,
	"IMMLQ" AS IMMLQ__mfg_leadtime_quantity,
	"IMLTPU" AS IMLTPU_leadtime_per_unit,
	"IMMPSP" AS IMMPSP_planning_fence_rule,
	"IMMRPP" AS IMMRPP_fixedvariable_leadtime,
	"IMITC" AS IMITC__issue_type_code,
	"IMORDW" AS IMORDW_order_with_yn,
	"IMMTF1" AS IMMTF1_planning_fence,
	"IMMTF2" AS IMMTF2_freeze_fence,
	"IMMTF3" AS IMMTF3_message_display_fence,
	"IMMTF4" AS IMMTF4_time_fence,
	"IMMTF5" AS IMMTF5_shipment_leadtime_offset,
	"IMMTF6" AS IMMTF6_supply_time_fence,
	"IMEXPD" AS IMEXPD_expedite_damper_days,
	"IMDEFD" AS IMDEFD_defer_damper_days,
	"IMSFLT" AS IMSFLT_safety_leadtime,
	"IMMAKE" AS IMMAKE_makebuy_code,
	"IMCOBY" AS IMCOBY_cobyproductintermediate,
	"IMLLX" AS IMLLX__low_level_code,
	"IMCMGL" AS IMCMGL_commitment_method,
	"IMCOMH" AS IMCOMH_specific_commitment_days,
	"IMCSNN" AS IMCSNN_configured_string_id_next_number,
	"IMURCD" AS IMURCD_user_reserved_code,
	"IMURDT" AS IMURDT_user_reserved_date,
	"IMURAT" AS IMURAT_user_reserved_amount,
	"IMURAB" AS IMURAB_user_reserved_number,
	"IMURRF" AS IMURRF_user_reserved_reference,
	"IMAVRT" AS IMAVRT_average_queue_hours,
	"IMUPCN" AS IMUPCN_upc_number,
	"IMSCC0" AS IMSCC0_aggregate_scc_code_pi0,
	"IMUMUP" AS IMUMUP_unit_of_measure_upc,
	"IMUMDF" AS IMUMDF_unit_of_measure_aggregate_upc,
	"IMUMS0" AS IMUMS0_unit_of_measure_sccpi0,
	"IMUMS1" AS IMUMS1_unit_of_measure_sccpi1,
	"IMUMS2" AS IMUMS2_unit_of_measure_sccpi2,
	"IMUMS3" AS IMUMS3_unit_of_measure_sccpi3,
	"IMUMS4" AS IMUMS4_unit_of_measure_sccpi4,
	"IMUMS5" AS IMUMS5_unit_of_measure_sccpi5,
	"IMUMS6" AS IMUMS6_unit_of_measure_sccpi6,
	"IMUMS7" AS IMUMS7_unit_of_measure_sccpi7,
	"IMUMS8" AS IMUMS8_unit_of_measure_sccpi8,
	"IMPILT" AS IMPILT_purchasing_internal_lead_time,
	"IMWTRQ" AS IMWTRQ_item_weight_required_yn,
	"IMPOC" AS IMPOC__i,
	"IMEXPI" AS IMEXPI_explode_item_10,
	"IMCONI" AS IMCONI_constraint_item_10,
	"IMORSP" AS IMORSP_allow_order_split_10,
	"IMCNSD" AS IMCNSD_consolidation_days,
	"IMCMDM" AS IMCMDM_commitment_date_method,
	"IMLECM" AS IMLECM_exp_date_calc_method,
	"IMBBDD" AS IMBBDD_best_before_default_days,
	"IMSBDD" AS IMSBDD_sell_by_default_days,
	"IMLEDD" AS IMLEDD_mfg_lot_effective_days,
	"IMPEFD" AS IMPEFD_purchasing_lot_effective_days,
	"IMU1DD" AS IMU1DD_user_lot_date_1_default_days,
	"IMU2DD" AS IMU2DD_user_lot_date_2_default_days,
	"IMU3DD" AS IMU3DD_user_lot_date_3_default_days,
	"IMU4DD" AS IMU4DD_user_lot_date_4_default_days,
	"IMU5DD" AS IMU5DD_user_lot_date_5_default_days,
	"IMTORG" AS IMTORG_transaction_originator,
	"IMUSER" AS IMUSER_user_id,
	"IMPID" AS IMPID__program_id,
	"IMJOBN" AS IMJOBN_work_station_id,
	"IMUPMJ" AS IMUPMJ_date_updated,
	"IMTDAY" AS IMTDAY_time_of_day 

-- INTO Integration.HSIPDTA71_F4101_item_master

FROM 
	-- ODBC link server name = ESYS_PROD for Canada.  
    OPENQUERY (ESYS_PROD, '

	SELECT
		IMITM,
		IMLITM,
		IMAITM,
		IMDSC1,
		IMDSC2,
		IMSRTX,
		IMALN,
		IMSRP1,
		IMSRP2,
		IMSRP3,
		IMSRP4,
		IMSRP5,
		IMSRP6,
		IMSRP7,
		IMSRP8,
		IMSRP9,
		IMSRP0,
		IMPRP1,
		IMPRP2,
		IMPRP3,
		IMPRP4,
		IMPRP5,
		IMPRP6,
		IMPRP7,
		IMPRP8,
		IMPRP9,
		IMPRP0,
		IMCDCD,
		IMPDGR,
		IMDSGP,
		IMPRGR,
		IMRPRC,
		IMORPR,
		IMBUYR,
		IMDRAW,
		IMRVNO,
		IMDSZE,
		CAST((IMVCUD)/10000.0 AS DEC(15,4)) AS IMVCUD,
		IMCARS,
		IMCARP,
		IMSHCN,
		IMSHCM,
		IMUOM1,
		IMUOM2,
		IMUOM3,
		IMUOM4,
		IMUOM6,
		IMUOM8,
		IMUOM9,
		IMUWUM,
		IMUVM1,
		IMSUTM,
		IMUMVW,
		IMCYCL,
		IMGLPT,
		IMPLEV,
		IMPPLV,
		IMCLEV,
		IMPRPO,
		IMCKAV,
		IMBPFG,
		IMSRCE,
		IMOT1Y,
		IMOT2Y,
		CAST((IMSTDP)/1000.0 AS DEC(15,3)) AS IMSTDP,
		CAST((IMFRMP)/1000.0 AS DEC(15,3)) AS IMFRMP,
		CAST((IMTHRP)/1000.0 AS DEC(15,3)) AS IMTHRP,
		IMSTDG,
		IMFRGD,
		IMTHGD,
		IMCOTY,
		IMSTKT,
		IMLNTY,
		IMCONT,
		IMBACK,
		IMIFLA,
		IMTFLA,
		IMINMG,
		IMABCS,
		IMABCM,
		IMABCI,
		IMOVR,
		IMWARR,
		IMCMCG,
		IMSRNR,
		IMPMTH,
		IMFIFO,
		IMLOTS,
		IMSLD,
		IMANPL,
		IMMPST,
		CAST((IMPCTM)/1000.0 AS DEC(15,3)) AS IMPCTM,
		CAST((IMMMPC)/1000.0 AS DEC(15,3)) AS IMMMPC,
		IMPTSC,
		IMSNS,
		IMLTLV,
		IMLTMF,
		IMLTCM,
		IMOPC,
		IMOPV,
		IMACQ,
		IMMLQ,
		CAST((IMLTPU)/100.0 AS DEC(15,2)) AS IMLTPU,
		IMMPSP,
		IMMRPP,
		IMITC,
		IMORDW,
		IMMTF1,
		IMMTF2,
		IMMTF3,
		IMMTF4,
		IMMTF5,
		IMMTF6,
		IMEXPD,
		IMDEFD,
		IMSFLT,
		IMMAKE,
		IMCOBY,
		IMLLX,
		IMCMGL,
		IMCOMH,
		IMCSNN,
		IMURCD,
		CASE WHEN IMURDT IS NOT NULL THEN DATE(DIGITS(DEC(IMURDT+ 1900000,7,0))) ELSE NULL END AS IMURDT,
		CAST((IMURAT)/100.0 AS DEC(15,2)) AS IMURAT,
		IMURAB,
		IMURRF,
		CAST((IMAVRT)/100.0 AS DEC(15,2)) AS IMAVRT,
		IMUPCN,
		IMSCC0,
		IMUMUP,
		IMUMDF,
		IMUMS0,
		IMUMS1,
		IMUMS2,
		IMUMS3,
		IMUMS4,
		IMUMS5,
		IMUMS6,
		IMUMS7,
		IMUMS8,
		IMPILT,
		IMWTRQ,
		IMPOC,
		IMEXPI,
		IMCONI,
		IMORSP,
		IMCNSD,
		IMCMDM,
		IMLECM,
		IMBBDD,
		IMSBDD,
		IMLEDD,
		IMPEFD,
		IMU1DD,
		IMU2DD,
		IMU3DD,
		IMU4DD,
		IMU5DD,
		IMTORG,
		IMUSER,
		IMPID,
		IMJOBN,
		CASE WHEN IMUPMJ IS NOT NULL THEN DATE(DIGITS(DEC(IMUPMJ+ 1900000,7,0))) ELSE NULL END AS IMUPMJ,
		IMTDAY

	FROM
		HSIPDTA71.F4101
--    WHERE
--        <insert custom code here>
--    ORDER BY
--        <insert custom code here>
')

--------------------------------------------------------------------------------


-- code to pull field names
-- full name = TTFFFF where TT = Table code, and FFFF is the field code
SELECT 
	RTRIM("FRDTAI")				AS data_item
	,"FRDTAT"					AS data_item_type
	,"FROWTP"					AS data_type
	,"FRDTAS"					AS data_item_size
	,ISNULL("FRCDEC", 0)		AS display_decimals
	,ISNULL("FRDSCR", 'zNA')	AS row_description 
    
FROM 

    OPENQUERY (ESYS_PROD, '

	SELECT
		t.FRDTAI
		,FRDTAT
		,FROWTP
		,FRDTAS
		,FRCDEC
		,FRDSCR
	FROM
		HSIPCOM93Q.F9210 t
		LEFT JOIN HSIPCOM93Q.F9202 d
		ON t.FRDTAI = d.FRDTAI AND
			d.FRLNGP = '' '' AND
			d.FRSYR = '' ''  
')
